# Generated by Django 5.0.6 on 2024-06-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylstore', '0002_disco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='imagen',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
