# Generated by Django 5.0.6 on 2024-07-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylstore', '0003_alter_disco_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='tracklist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
