# Generated by Django 5.0.6 on 2024-07-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinylstore', '0004_disco_tracklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disco',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
